config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.apps import MaterialsConfig
from materials.views import *

app_name = MaterialsConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    ]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_pass, password_reset_view, verify_email_view, LetterSending

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/new_pass', generate_pass, name='new_pass'),
    path('verification/<int:key>/', verify_email_view, name='verification'),
    path('letter_sending/', LetterSending.as_view(), name='letter_sending'),
    path('forgot_password/', password_reset_view, name='password_reset'),

]

materials/models.py
from django.db import models
from django.urls import reverse

NULLABLE = {'blank': True, 'null': True}


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.CharField(max_length=250, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    date_create = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    preview = models.ImageField(upload_to='blog/', null=True, blank=True, verbose_name='Изображение')
    is_published = models.BooleanField(default=True, verbose_name='Опубликована или нет')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

materials/views.py
from materials.models import Article
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.contrib.auth.mixins import LoginRequiredMixin


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('materials:list')
    login_url = '/users'

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    login_url = '/users'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    pk_url_kwarg = 'pk'
    login_url = '/users'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset=queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'body', 'preview',)
    login_url = '/users'

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('materials:list')
    login_url = '/users'

materials/templates/materials/article_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
         <div class="row">
             <div class="col-6">
                 <div class="card">
                     <div class="card-body">
                         <form method="post">
                             {% csrf_token %}
                             <p> Хотите удалить материал "{{object.title}}"?</p>
                             <button type="submit" class="btn btn-danger">Подтвердить</button>
                             <a href="{% url 'materials:list' %}" class="btn btn-primary">Отмена</a>
                         </form>
                     </div>
                 </div>
             </div>
         </div>
    </div>

{% endblock %}

materials/templates/materials/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <a href="{% url 'materials:create' %}" class="btn btn-primary my-2">Добавить материал</a>
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">{{ object.title }} ({{object.slug}})</h1>
                    <div class="col-6">
                        <img src="{% mediapath object.preview %}" style="height: 300px">
                    </div>
                    <p align="left">{{ object.body }}</p>
                        <a href="{% url 'materials:update' object.pk %}" class="btn btn-primary my-2">Редактирование</a>
                        <a href="{% url 'materials:delete' object.pk %}" class="btn btn-primary my-2">Удалить</a>
                    <h6>Просмотры: {{ object.views_count }}</h6>
                </div>
            </div>
        </section>
    </div>
</div>

{% endblock %}

materials/templates/materials/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                     <div class="card-body">
                         <form method="post" enctype="multipart/form-data">
                             {% csrf_token %}
                             {{form.as_p}}
                                 <button type="submit" class="btn btn-primary">
                                     {% if object %}
                                     Сохранить
                                     {% else %}
                                     Создать

                                    {% endif %}
                                 </button>
                         </form>
                     </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/article_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <a href="{% url 'materials:create' %}" class="btn btn-primary my-2">Добавить материал</a>
            </div>
        </div>
    </div>
<div class="row">
    {% if object_list %}
        {% for object in object_list %}
        <div class="col-md-4">
            <h2>{{ object.title }}</h2>
            <p>{{ object.body|slice:100 }}</p>
            <p>
                <a class="btn btn-secondary" href="{% url 'materials:view' object.pk %}">Смотреть подробнее</a>
            </p>
        </div>
        {% endfor %}
    {% else %}
    <h4>Статей нет, но Вы можете что-нибудь написать.</h4>

    {% endif %}

</div>
{% endblock %}