config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_pass, password_reset_view, verify_email_view, LetterSending

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/new_pass', generate_pass, name='new_pass'),
    path('verification/<int:key>/', verify_email_view, name='verification'),
    path('letter_sending/', LetterSending.as_view(), name='letter_sending'),
    path('forgot_password/', password_reset_view, name='password_reset'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from materials.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    verification_key = models.IntegerField(verbose_name='ключ', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import FormMixin
from users.models import User


class UserRegisterForm(FormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(FormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, FormView, TemplateView

from catalog.forms import ContactForm
from .models import User
from .forms import UserRegisterForm, UserProfileForm
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import login


class LetterSending(TemplateView):
    template_name = 'users/succsess_letter.html'
    extra_context = {
        'title': 'Завершение регистрации'
    }


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:letter_sending')
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        self.object.is_active = False
        self.object.verification_key = ''.join([str(random.randint(0, 9)) for _ in range(0, 9)])
        self.object.save()
        send_mail(
            subject='Регистрация',
            message=f'Вы зарегистрировались на нашем сайте. Для подтверждения регистрации перейдите по ссылке: '
                    f'http://127.0.0.1:8000/users/verification/{self.object.verification_key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_pass(request):
    password = User.objects.make_random_password()
    request.user.set_password(password)
    request.user.save()
    send_mail(
        subject='Восстановление пароля',
        message=f'Ваш новый пароль - {password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    return redirect(reverse('users:login'))


def verify_email_view(request, key):
    if request.method == 'GET':
        user = User.objects.get(verification_key=int(key))
        user.is_active = True
        user.save()

        context = {
            'object_list': User.objects.filter(verification_key=key)
        }
    login(request, user)
    return render(request, 'users/verification.html', context)


def password_reset_view(request):
    if request.method == 'POST':
        user = User.objects.get(email=request.POST.get('email'))
        new_password = User.objects.make_random_password()
        user.set_password(new_password)
        user.save()
        send_mail(
            subject='Сброс пароля',
            message=f'Вы запросили сброс пароля. Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[request.POST.get('email')]
        )
        return redirect('users:login')

    return render(request, 'users/reset_password.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Войти
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Войти</button>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-outline-danger">Забыли пароль?</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Регистрация</h3>
            </div>

            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{form.errors}}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Восстановить пароль
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            <input type="text" name="email" class="form-control" id="email" placeholder="Электронная почта" required>
                        <br>
                        <button type="submit" class="p-2 btn btn-outline-primary">Отправить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>

{% endblock %}

users/templates/users/succsess_letter.html
<!DOCTYPE html>
{% extends 'catalog/base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Завершение регистрации</title>
</head>
<body>
 <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Вам на почту отправлено письмо.</p>
                    <p class="card-text">Для подтверждения регистрации перейдите по ссылке из письма.</p>
                </div>
            </div>
</body>
</html>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Профиль</h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.errors}}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:new_pass' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/verification.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Регистрация завершена успешно!</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}