catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import *
from catalog.views import ContactFormView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactFormView.as_view(), name='contacts'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('categories/', show_category_list, name='categories'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('categories/<int:pk>/', ProductDetailsByCategory.as_view(), name='product_cat'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('version/', VersionListView.as_view(), name='version'),

    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.apps import MaterialsConfig
from materials.views import *

app_name = MaterialsConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    ]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_pass, password_reset_view, verify_email_view, LetterSending

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/new_pass', generate_pass, name='new_pass'),
    path('verification/<int:key>/', verify_email_view, name='verification'),
    path('letter_sending/', LetterSending.as_view(), name='letter_sending'),
    path('forgot_password/', password_reset_view, name='password_reset'),

]

catalog/models.py
from django.db import models, connection

from config import settings
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(blank=True, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute(f'TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE')


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(blank=True, verbose_name='описание')
    image = models.ImageField(upload_to='images/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date_create = models.DateField(auto_now_add=True, verbose_name='дата создания')
    date_update = models.DateField(auto_now=True, verbose_name='дата изменения')
    user_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.name}, {self.category}, {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute(f'TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE')


class Version(models.Model):
    SIGN_CHOICES = (('active', 'Активна'), ('no_active', 'Не активна'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="get_ver", verbose_name='продукт')
    number_ver = models.CharField(max_length=100, verbose_name='номер версии')
    name_ver = models.CharField(max_length=100, verbose_name='название версии')
    sign_ver = models.CharField(max_length=50, choices=SIGN_CHOICES, verbose_name='признак версии')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'{self.product} - {self.number_ver}/({self.name_ver})'

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from django.forms.models import BaseInlineFormSet


class FormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ContactForm(FormMixin, forms.Form):
    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))


class ProductForm(FormMixin, forms.ModelForm):
    stop_list = [
        'КАЗИНО', 'КРИПТОВАЛЮТА', 'КРИПТА', 'БИРЖА', 'ДЕШЕВО', 'БЕСПЛАТНО',
        'ОБМАН', 'ПОЛИЦИЯ', 'РАДАР'
    ]

    class Meta:
        model = Product
        exclude = ('user_owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for word in ProductForm.stop_list:
            if word in cleaned_data.upper():
                raise forms.ValidationError('Запрещенные слова в названии продукта')
            else:
                continue

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        for word in ProductForm.stop_list:
            if word in cleaned_data.upper():
                raise forms.ValidationError('Запрещенные слова в описании продукта')
            else:
                continue

        return cleaned_data


class VersionForm(FormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class VersionFormSet(forms.BaseInlineFormSet):

    def clean(self):
        super().clean()
        direct_ancestor_count = 0
        for form in self.forms:
            if form['is_direct_ancestor'].data:
                direct_ancestor_count += 1
                if direct_ancestor_count > 1:
                    raise forms.ValidationError('Активной может быть только одна версия!')

catalog/views.py
from catalog.models import Product, Version, Category
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView, TemplateView, FormView
from django.urls import reverse_lazy, reverse
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from catalog.forms import ProductForm, VersionForm, ContactForm
from catalog.services import get_categories


class IndexView(TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'Главная'
    }


# class CategoryListView(LoginRequiredMixin, ListView):
#     model = Category
#     extra_context = {
#         'title': 'Все категории'
#     }
@login_required
def show_category_list(request):
    context = {'object_list': get_categories(),
               'title': 'Все категории продуктов'}
    return render(request, 'catalog/category_list.html', context)


class ProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/products.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        active_version = Version.objects.filter(sign_ver='active')
        context['title'] = 'Все продукты'

        for product in context['object_list']:
            version = active_version.filter(product=product)
            if version:
                product.version = {
                    'name_ver': version[0].name_ver,
                    'number_ver': version[0].number_ver
                }

        return context


class ProductDetailsByCategory(ListView):
    model = Product
    template_name = 'catalog/products_cat.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(category_id=self.kwargs.get('pk'))
        print(queryset[0].category)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context['object_list'] = Product.objects.filter(category_id=category_item.pk)
        context['title'] = f'Все продукты категории: {category_item.name}'

        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product.html'
    context_object_name = 'product'
    pk_url_kwarg = 'pk'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Подробнее о продукте'

        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def get_success_url(self):
        return reverse('catalog:update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormSet(self.request.POST, instance=self.object)
        else:
            formset = VersionFormSet(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')


class VersionListView(LoginRequiredMixin, ListView):
    model = Version
    context_object_name = 'version'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_ver='active')

        return queryset


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'catalog/contact.html'
    success_url = reverse_lazy('/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context

    def form_valid(self, form):
        if form.is_valid():
            print(form.cleaned_data)
        return redirect('/')

catalog/templates/catalog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                     <div class="card-body">
                         <form method="post">
                             {% csrf_token %}
                             {{form.as_p}}
                                 <button type="submit" class="btn btn-primary">Добавить</button>
                             </form>
                         </form>
                     </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ title }}</title>
        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    </head>
    <body>
    {% include 'catalog/includes/inc_menu.html' %}

      <div class="header">
          {% if request.path != '/' %}
                <p align="right"> <a href="{% url 'catalog:index' %}" class="home-button">Главная страница </a>
          </p>
        {% endif %}
      </div>

    <div class="pricing-header text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
            продать</p>
    </div>

    <body>
      {% block content %}
      {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
                </div>
<!--                <div class="col-4 col-md">-->
<!--                    <h5> Категории</h5>-->
<!--                    <ul class="list-unstyled text-small">-->

<!--                        <li><a class="text-muted" href="{% url 'catalog:product_cat' 1 %}"> Рассылки</a></li>-->
<!--                        <li><a class="text-muted" href="{% url 'catalog:product_cat' 2 %}"> Телеграм боты</a></li>-->
<!--                        <li><a class="text-muted" href="{% url 'catalog:product_cat' 3 %}"> Полезные утилиты</a></li>-->
<!--                        <li><a class="text-muted" href="{% url 'catalog:product_cat' 4 %}"> Веб-приложения</a></li>-->
<!--                        <li><a class="text-muted" href="{% url 'catalog:product_cat' 5 %}"> Микросервисы</a></li>-->
<!--                    </ul>-->
<!--                </div>-->
                <div class="col-4 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="{% url 'materials:list' %}">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-4 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>
      <style>
        .card-text {
          overflow-wrap: break-word;
        }
      </style>
    </body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="center">
        <h1>{{title}}:</h1>
    </div>
    {% for object in object_list %}
    <ul class="list-unstyled text-small">
        <a class="text-muted" href="{% url 'catalog:product_cat' object.pk %}">{{object}}</a>
    </ul>
    {% endfor %}
    {% endblock %}
</div>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}
<!--<h1>{{title}}</h1>-->
<div class="row">


<div class="col">
            <div class="card">
                <h5 class="card-title">Контакты:</h5>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-15">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-15">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-15">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
    </div>

        <div class="col">
            <div class="card>">
                <h5 class="card-title">Оставить сообщение:</h5>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <button type="submit">Отправить</button>
                </form>
            </div>
        </div>


        {% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-15">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-15">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-15">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                            <input class="btn btn-primary w-100" type="submit" value="Send"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }} {{ product.name }}</h1>
</div>
<div class="container">
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <img src="{% mediapath product.image %}" style="height: 300px"/>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Продукт</td>
                                <td>{{ product.name }}</td>
                            </tr>
                            <tr>
                                <td>Версия</td>
                                <td><h6 class="card-text">Версия - {{ product.get_ver.all.first.number_ver }}</h6> </td>
                            </tr>
                            <tr>
                                <td>Описание</td>
                                <td>{{ product.description }}</td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td>{{ product.price }} руб.</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <a class="p-2 btn btn-outline-primary" href="/products">Назад</a>
                        <a class="p-2 btn btn-outline-primary" href="#">Купить</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


    {% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
         <div class="row">
             <div class="col-6">
                 <div class="card">
                     <div class="card-body">
                         <form method="post">
                             {% csrf_token %}
                             <p> Хотите удалить продукт "{{product.name}}"?</p>
                             <button type="submit" class="btn btn-danger">Подтвердить</button>
                             <a href="{% url 'catalog:products' %}" class="btn btn-primary">Отмена</a>
                         </form>
                     </div>
                 </div>
             </div>
         </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Добавление продукта
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a class="p-2 btn btn-outline-primary" href="/products">Назад</a>
            </div>
        </div>
    </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Версия
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p}}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
</form>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить продукт</a>
</div>

<style>
    .product-card {
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    .edit-button {
      margin-top: 10px;
      border-top: 1px solid #ccc;
      padding-top: 10px;
    }

    .center {
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="center">
            <h1>{{ title }}:</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card product-card">
                <div class="card-body">
                    <!--                <img src="{{ product.image|mediapath }}" style="height: 300px"/></img>-->
                    <img src="{% mediapath product.image %}" style="height: 300px"/>
                    <h5 class="card-title">{{ product.name }}</h5>
                    {% if product.version %}
                        <h6 class="card-text">Версия - {{ product.version|get_item:'number_ver' }} ({{ product.version|get_item:'name_ver' }})</h6>
                    {% endif%}
                    <p class="card-text">{{ product.description | truncatechars:50}}</p>
                    <h6 class="card-subtitle mb-2 text-muted">{{product.price}} рублей</h6>
                    <p><a class="btn btn-secondary" href="/product/{{product.pk}}" role="button">Подробнее &raquo;</a>
                    </p>
                    <a href="{% url 'catalog:update' product.pk %}" class="btn btn-primary my-2">Редактирование</a>
                    <a href="{% url 'catalog:delete' product.pk %}" class="btn btn-primary my-2">Удалить</a>
                </div>
            </div>
            <div class="card-footer">
                    <p class="card-text mute">Добавлено пользователем {{product.user_owner|default:"-"}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/products_cat.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить продукт</a>
    <a class="btn btn-outline-primary" href="{% url 'catalog:categories' %}">Назад</a>
</div>

<style>
    .product-card {
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    .edit-button {
      margin-top: 10px;
      border-top: 1px solid #ccc;
      padding-top: 10px;
    }

    .center {
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="center">
            <h1>{{ title }}:</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        {% for object in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card product-card">
                <div class="card-body">
                    <!--                <img src="{{ product.image|mediapath }}" style="height: 300px"/></img>-->
                    <img src="{% mediapath object.image %}" style="height: 300px"/>
                    <h5 class="card-title">{{ object.name }}</h5>
                    {% if product.version %}
                        <h6 class="card-text">Версия - {{ object.version|get_item:'number_ver' }} ({{ object.version|get_item:'name_ver' }})</h6>
                    {% else %}
                        <br/>
                    {% endif%}
                    <p class="card-text">{{ object.description | truncatechars:50}}</p>
                    <h6 class="card-subtitle mb-2 text-muted">{{object.price}} рублей</h6>
                    <p><a class="btn btn-secondary" href="/product/{{object.pk}}" role="button">Подробнее &raquo;</a>
                    </p>
                    <a href="{% url 'catalog:update' object.pk %}" class="btn btn-primary my-2">Редактирование</a>
                    <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-primary my-2">Удалить</a>
                </div>
            </div>
            <div class="card-footer">
                    <p class="card-text mute">Добавлено: {{object.user_owner|default:"-"}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}